"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;
var _default = {
  important: true,
  separator: ":",
  theme: {
    borderWidth: {
      default: "1px",
      semi: "0.5px",
      "0": "0",
      "2": "2px",
      "3": "3px",
      "5": "5px",
      "8": "8px"
    },
    height: {
      auto: "auto",
      full: "100%",
      screen: "100vh"
    },
    width: {
      auto: "auto",
      full: "100%",
      screen: "100vw"
    },
    zIndex: {
      "0": 0,
      "10": 10,
      "20": 20,
      "30": 30,
      // This is the modal level
      "40": 40,
      "50": 50,
      "100": 100
    }
  },
  variants: {
    alignItems: [],
    backgroundOpacity: [],
    backgroundPosition: [],
    backgroundSize: [],
    borderRadius: [],
    borderOpacity: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: [],
    cursor: [],
    display: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    fontFamily: [],
    fontSize: [],
    fontStyle: [],
    fontWeight: [],
    height: [],
    inset: [],
    lineHeight: [],
    justifyContent: [],
    margin: [],
    objectFit: [],
    opacity: [],
    overflow: [],
    padding: [],
    position: [],
    textAlign: [],
    textDecoration: [],
    userSelect: [],
    visibility: [],
    whitespace: [],
    width: [],
    zIndex: []
  },
  corePlugins: {
    accessibility: false,
    alignContent: false,
    alignSelf: false,
    appearance: false,
    backgroundAttachment: false,
    backgroundColor: false,
    backgroundRepeat: false,
    borderCollapse: false,
    borderColor: false,
    boxSizing: false,
    container: false,
    clear: false,
    divideColor: false,
    divideOpacity: false,
    divideWidth: false,
    fill: false,
    flex: false,
    float: false,
    fontSmoothing: false,
    gap: false,
    gridAutoFlow: false,
    gridColumn: false,
    gridColumnEnd: false,
    gridColumnStart: false,
    gridRow: false,
    gridRowEnd: false,
    gridRowStart: false,
    gridTemplateColumns: false,
    gridTemplateRows: false,
    letterSpacing: false,
    listStylePosition: false,
    listStyleType: false,
    maxHeight: false,
    maxWidth: false,
    minHeight: false,
    minWidth: false,
    objectPosition: false,
    order: false,
    outline: false,
    placeholderColor: false,
    placeholderOpacity: false,
    pointerEvents: false,
    resize: false,
    rotate: false,
    scale: false,
    skew: false,
    space: false,
    stroke: false,
    strokeWidth: false,
    tableLayout: false,
    textColor: false,
    textOpacity: false,
    textTransform: false,
    transform: false,
    transformOrigin: false,
    transitionDelay: false,
    transitionDuration: false,
    transitionProperty: false,
    transitionTimingFunction: false,
    translate: false,
    verticalAlign: false,
    wordBreak: false
  }
};
exports.default = _default;
module.exports = exports.default;